# Generated by Django 2.2 on 2020-05-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200518_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='姓名'),
        ),
    ]
