# Generated by Django 2.2 on 2020-05-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_firmuser',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='is_firmuser',
            field=models.BooleanField(null=True, verbose_name='是否是企业账号'),
        ),
    ]
