# Generated by Django 2.2 on 2020-05-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200518_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='projectplace',
        ),
    ]
