# Generated by Django 2.2 on 2020-05-18 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_image_projectplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwork',
            name='workplaceid',
        ),
        migrations.AddField(
            model_name='userwork',
            name='projectplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Projectplace', verbose_name='工作的场地编号'),
        ),
    ]
