# Generated by Django 2.2 on 2020-05-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200518_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwork',
            name='description',
            field=models.CharField(max_length=256, null=True, verbose_name='工作简介'),
        ),
    ]
