# Generated by Django 2.2 on 2020-05-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_monitorinfomation_monitorimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='releasedata',
            new_name='releasedate',
        ),
        migrations.AddField(
            model_name='salary',
            name='sicklevel',
            field=models.IntegerField(null=True, verbose_name='病假'),
        ),
    ]
