# Generated by Django 2.2 on 2020-05-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20200519_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='sicklevel',
            new_name='sickleave',
        ),
    ]
