# Generated by Django 2.2 on 2020-05-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20200519_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=32, null=True, verbose_name='员工编号'),
        ),
    ]
