# Generated by Django 2.2 on 2020-05-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_user_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=256, null=True, verbose_name='通知')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='发布时间')),
            ],
        ),
    ]
