# Generated by Django 2.2 on 2020-05-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20200519_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=64, null=True, verbose_name='家庭住址'),
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=32, null=True, verbose_name='联系电话'),
        ),
    ]
