# Generated by Django 2.2 on 2020-05-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20200519_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmemt',
            name='bossname',
            field=models.CharField(max_length=32, null=True, verbose_name='部门负责人名字'),
        ),
        migrations.AddField(
            model_name='departmemt',
            name='departmentid',
            field=models.CharField(max_length=64, null=True, verbose_name='部门编号'),
        ),
    ]
