# Generated by Django 2.2 on 2020-05-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20200519_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='createaddress',
            field=models.CharField(max_length=32, null=True, verbose_name='注册地点'),
        ),
        migrations.AddField(
            model_name='company',
            name='shortname',
            field=models.CharField(max_length=32, null=True, verbose_name='简称'),
        ),
    ]
