# Generated by Django 2.2 on 2020-05-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20200520_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uname',
            field=models.CharField(max_length=32, null=True, verbose_name='真实姓名'),
        ),
    ]
